AB#182524: Novel compound names
AI4Green/AI4Green pull request #92
Opened 2024-10-07 13:44 UTC by JoeDavies-6

# Overview

Validate novel compound names and handle consistently

## Azure Boards

- AB#182524

2024-10-07 14:17 UTC, dcl10 requested changes

2024-10-07 14:17 UTC, dcl10 commented on Webapp/sources/services/novel_compound.py
> +        return compound_name
For this bit you can replace the two regexes with just the one: `([\"\'])(.+?)\1,\s*\d+`. Paste it into the following link and select Python on the left hand side to check: https://regex101.com/

2024-10-07 14:31 UTC, dcl10 approved these changes

2024-10-08 08:29 UTC, dcl10 approved these changes

2024-10-08 12:42 UTC, psytb6 approved these changes

2024-10-08 12:47 UTC, merged