AB#183155: Rename workgroup functionality
AI4Green/AI4Green pull request #93
Opened 2024-10-23 13:40 UTC by psytb6

# Overview

Added functionality to rename workgroup names

## Azure Boards

- AB#183155

2024-10-23 14:43 UTC, dcl10 requested changes

2024-10-23 14:43 UTC, dcl10 commented on Webapp/sources/services/workgroup.py
> +        the new name is stripped of spaces, and lowered to be entirely lowercase. Likewise, all
```suggestion
        The new name is stripped of spaces, and lowered to be entirely lowercase. Likewise, all
```

2024-10-23 14:43 UTC, dcl10 commented on Webapp/sources/static/js/manage_workgroup.js
> +      "Are you sure you want to remove this user entirely from the Workgroup? They will also be removed from any Workbooks they are part of within this Workgroup.",
```suggestion
      "Are you sure you want to remove this user entirely from the Workgroup? They will also be removed from any Workbooks that are part of this Workgroup.",
```

2024-11-21 13:23 UTC, dcl10 approved these changes

2024-11-21 13:49 UTC, JoeHeeley2 approved these changes

2024-11-22 12:15 UTC, merged